name: Node.js CI/CD

on:
  push:
    branches: 
        - main
        - dev
        - '**'
    tags:
        - 'v*'
  pull_request:  
    branches: 
        - main
        - dev
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: '${{ matrix.node-version }}'
        
        - name: Cache node modules
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ matrix.node-version }}-npm-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
                ${{ runner.os }}-node-${ matrix.node-version }}-