name: CI/CD with Cypress
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
    cypress-tests:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: cypress
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20'

        - name: Install dependencies
          run: npm install

        - name: Run Cypress tests
          run: npx cypress run

        - name: Upload test results
          uses: actions/upload-artifact@v4
          with:
            name: cypress-results
            path: cypress/results